language: python
python:
- '3.6'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIII2UVMSV
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: midrc_dictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/midrc_dictionary
    all_branches: true
  secret_access_key:
    secure: OOrV8BP+q1dzpZqbGmBypZcDEvOcfyzeeP4fK8I2LqoFv+mgePJ4x83WMdWkFYvE98Z1oTrfCZbSIjmfUjaKYGPbkz4J79f8ZfRkgp3ZvGIpxTXlHtHS0PEBbOadozYBofe9PJMPs87jNnQ89rw8YSyZfxYiz9ZO4oAeV9ElLHbbQCo+iQmf/4pgoYCcISmFbwB5R1uU2QSWMCNdeNnCOLf2H8W6R8OTIM9f946SVEs7PmHsxqlqAHq6GaPx2P2J8fLXUVa1J2DNorhmccfWfaqSyAhuoX7QZIeqCb+warGxNNJ5ihQr21hr6OaSMIrXtk/inUi0ov8WSDiSTHP5trEKg4DXwiUa9DaYrkZ0LiPWgaOOJ8dFRdQWC950jLfv37q0tRZKB7/Qz4/TVjNiKvzWBPf4/Y3L5W0267S0hM7BH3EIgWrINAzSKIGMLTaz8/XCBggQkraE8+mvIU8le7lel/4qBsvKNrMdTMP54DAsH0149GMlhtaHSyYpl7HWkdUhzKw74daBFtSU6ETwssiCuStXPCElkbwbXYvwZH0QZhBX1HbGiV9sTCHaIMZ1CczxUC19Ye4NyA+lOz2MDUgC2kkw1CD8vTLMiQYuQRIwrK+pBW32YRSl49qV2laFiw4BrMx3GAKH6BeyJJ0MrMF4VhoslL1dvhmJymPZ6rY=
